In [1]:
import cv2

# Load the image
img = cv2.imread(r"D:\Babe\IMG_20231024_190545.jpg")
#imread() is used to take load a image
#imread() takes 2 arguments 1. image path, 2.0,1,-1(0-> grey scale,1-RGB,-1-->unchanged)
# Print the image array
print(img)
#cv comes with mandatory numpy library so when we try to print the image above it print the array value of the img#imread() is used to take load a image
#imread() takes 2 arguments 1. image path, 2.0,1,-1(0-> grey scale,1-RGB,-1-->)
# Display the original image
cv2.imshow("original", img)
#cv comes with mandatory numpy library so when we try to print the image above it print the array value of the img
#to see the image we use ## imshow() its also takes 2 parameters : 1. Window name 2.image

# Wait for any key press
cv2.waitKey(0)

# Close all OpenCV windows
cv2.destroyAllWindows()


[[[ 74 107 157]
  [ 73 106 156]
  [ 70 105 155]
  ...
  [250 253 255]
  [250 253 255]
  [250 253 255]]

 [[ 74 107 157]
  [ 73 106 156]
  [ 71 106 156]
  ...
  [250 253 255]
  [250 253 255]
  [250 253 255]]

 [[ 72 107 157]
  [ 72 107 157]
  [ 72 107 157]
  ...
  [250 253 255]
  [250 253 255]
  [250 253 255]]

 ...

 [[  0   6  16]
  [  0   6  16]
  [  0   5  15]
  ...
  [ 79 124 175]
  [ 78 123 174]
  [ 79 124 175]]

 [[  0   5  15]
  [  0   5  15]
  [  0   5  15]
  ...
  [ 80 125 176]
  [ 78 123 174]
  [ 78 123 174]]

 [[  0   5  15]
  [  0   6  16]
  [  0   6  16]
  ...
  [ 77 122 173]
  [ 75 120 171]
  [ 74 119 170]]]


## use of resize()
it takes two parameter as u can see 1.width, 2.heigh

In [6]:
img1 = cv2.resize(img,(500,750))#width ,height
cv2.imshow("Resized image",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

## use of flip()
its takes 2 parameter 
1. image
2. 0,1,-1
    1. img2=cv2.flip(img1,0) #  Vertically flip
    2. img3=cv2.flip(img1,1) # normal
    3. img4=cv2.flip(img1,-1) # horizontally flip

   

In [13]:
img2=cv2.flip(img1,0) #  Vertically flip
cv2.imshow("Vertically flip",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
img3=cv2.flip(img1,1) # normal
cv2.imshow("normal image",img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
img4=cv2.flip(img1,-1) # horizontally flip
cv2.imshow("horizontally flip image",img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

For Grey Scale image

In [16]:
img = cv2.imread(r"D:\Babe\IMG_20231024_190545.jpg",0)
img1 = cv2.resize(img,(500,800))
cv2.imshow("grey", img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

For BGR channel image

In [17]:
img = cv2.imread(r"D:\Babe\IMG_20231024_190545.jpg",1)
img1 = cv2.resize(img,(500,800))
cv2.imshow("BGR", img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

For Unchanged channel - it gives more clear or we can say deatiled or enhanced image then original one

In [19]:
img = cv2.imread(r"D:\Babe\IMG_20231024_190545.jpg",-1)
img1 = cv2.resize(img,(500,800))
cv2.imshow("Unchanged", img1)
cv2.waitKey(0)
cv2.destroyAllWindows()